---
- name: Setup Mysql with accounts db and remote login
  hosts: dbsrvgrp
  gather_facts: no
  tasks:
    - name: Installing Mysql Service and dependencies
      package:
        name: "{{item}}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      loop:
        - mysql-server
        - mysql-client
        - python-mysqldb
        - python3-mysqldb
        - libmysqlclient-dev
      ignore_errors: yes
      tags:
        - package

    - name: Start and enable mysql service
      service:
        name: mysql
        
    - name: Setup Local hostname
      ansible.builtin.hostname:
        name: "{{hostname}}"

    - name: Setup DB Password
      shell: |
        echo "DATABASE_PASS='admin123'" >> ~/.bash_profile
        source ~/.bash_profile

    - name: Update all Installed packages using YUM module
      ansible.builtin.yum:  
        name: "*"
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status  # move the output of this block into "yum_update_statue" variable

    - name: Install epel repo
      yum: name=epel-release state=present

    - name: Install python bindings for SELinux
      yum: name={{item}} state=present
      with_items:
      - libselinux-python
      - libsemanage-python
    
    - name: Test to see is SELinux is running
      command: getenforce
      register: sestatus
      changed_when: false
   
    - name: Installing Mysql Service and dependencies
      ansible.builtin.yum:
        name: 
          - git
          - zip
          - unzip
          - mariadb-server
          - MySQL-python # dependencies for createing a user in the database
        state: present

    - name: Start and enable mysql service
      service:
        name: mariadb
        state: started
        enabled: yes
      tags:
        - svc

    - name: creating mysql user
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        host: '%'
        state: present


    - name: Creating accounts DB
      mysql_db:
        name: "{{dbname}}"
        state: present

    - name: Enable remote login to mysql svc
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
        backup: yes
      notify:
        - Restart mysql
      tags:
        - conf
    - name: Edit my.cnf to allow root at localhost
      shell: |
        sudo echo "skip-grant-table" >> /etc/my.cnf.d/server.cnf
        sudo systemctl restart mariadb

    - name: Restore the dump file from the application
      shell: |
        cd /tmp/
        git clone -b local-setup https://github.com/devopshydclub/vprofile-project.git
        mysqladmin -u root password "$DATABASE_PASS"
        sudo systemctl restart mariadb
        sleep 15;
        mysql -u root -p"DATABASE_PASS" -e "UPDATE mysql.user SET Password=PASSWORD('$DATABASE_PASS') WHERE User='root'"
        mysql -u root -p"DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
        mysql -u root -p"DATABASE_PASS" -e "DELETE FROM mysql.user WHERE User=''"
        mysql -u root -p"DATABASE_PASS" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
        mysql -u root -p"DATABASE_PASS" -e "FLUSH PRIVILEGES"
        mysql -u root -p"DATABASE_PASS" -e "grant all privileges on accounts.* TO 'admin'@'localhost' identified by 'admin123'"
        mysql -u root -p"DATABASE_PASS" -e "grant all privileges on accounts.* TO 'admin'@'%' identified by 'admin123'"
        sudo systemctl restart mariadb
        sleep 15;
        mysql -u root -p"DATABASE_PASS" accounts < /tmp/vprofile-project/src/main/resources/db_backup.sql
        mysql -u root -p"DATABASE_PASS" -e "FLUSH PRIVILEGES"
        sudo systemctl restart mariadb
        sleep 15;

    - name: FirewallD rules
      firewalld:
        permanent: yes
        immediate: yes
        service: "{{ item }}"
        state: enabled
      with_items:
        - ssh
        - mysql

  handlers:
    - name: Restart mysql
      service:
        name: mariadb
        state: restarted

